[package]
edition = "2024"
name = "dbt-yaml_derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = { version = "1.0", features = ["proc-macro"] }
quote = { version = "1.0", features = ["proc-macro"] }
syn = { version = "2.0", features = ["full"] }
